name: lgformer
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.aliyun.com/anaconda/pkgs/main/
  - https://mirrors.aliyun.com/anaconda/cloud/conda-forge/
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.10.0
  - torchvision=0.11.0
  - torchaudio=0.10.0
  - numpy=1.19.2
  - pip:
    - requests
    - filelock
    - tqdm
    - timm
    - mmcv-full==1.3.12
    - mmsegmentation==0.17.0
    - ftfy
    - regex
    - scipy
    - scikit-image
    - pycocotools==2.0.2
    - opencv-python==4.5.3.56
    - tokenizers==0.8.1rc1
    - h5py
    - transformers==4.19.2